### ISSUE TITLE
Permisions

### ISSUE THREAD

**Issue by Beyondem** [Toxblh/samsung-tv-control#1]
I've tried all the libraries, and this is the only one that seems to actually work! 

However, every single time I try to send a command, it requires me to confirm the permission on the TV; making it not practical.

Any fix for this?

**Comment by Toxblh** [comment]
Hey! Ou I didn’t update it 😅
Yes in 1h I’ll update it and first conection return to you a token which need to save in config and all will be work without reconfirm

**Comment by Beyondem** [comment]
Awesome, I'll look out for it! 

Thank you!

**Comment by Toxblh** [comment]
@Beyondem in version v1.1.0 
Also, function `isAvaliable` now is better and migrate to promise.

**Comment by Toxblh** [comment]
Yes, may bad in the example.

**Comment by Beyondem** [comment]
Yeah, the example needs to be updated. Works by adding the .default! 

Awesome, thank you! Now I can automate my tv 😄

**Comment by Toxblh** [comment]
I'll add soon also open apps.
