### ISSUE TITLE
Can't use on KU6400

### ISSUE THREAD

**Issue by ilteoood** [Toxblh/samsung-tv-control#13]
Hi,
I'm using your library with this configuration:

```js
const config = {
    debug: true, // Default: false
    ip: '192.168.1.244',
    mac: 'F8...3C',
    name: 'NodeJS-Test', // Default: NodeJS
}
```
But I have authorization problem, even with access notification disabled: I can see the remote with allowed status, but it can't execute any command

`
TV is avaliable
message {
  "event": "ms.channel.unauthorized"
}
message {
  "event": "ms.error",
  "data": {
    "message": "No Authorized"
  }
}
TV is avaliable
message {
  "event": "ms.channel.unauthorized"
}
message {
  "event": "ms.channel.clientDisconnect",
  "data": {
    "id": "914c2590-3a9b-11ea-8bda-09a15a0e9908",
    "connectTime": 1579425042025,
    "attributes": {
      "name": "Tm9kZUpTIFJlbW90ZQ=="
    },
    "deviceName": "Tm9kZUpTIFJlbW90ZQ==",
    "isHost": false
  }
}
message {
  "event": "ms.error",
  "data": {
    "message": "No Authorized"
  }
}
message {
  "event": "ms.channel.clientConnect",
  "data": [
    {
      "id": "031fbaf0-3a2a-11ea-8bda-09a15a0e9908",
      "connectTime": 1579376270367,
      "attributes": {
        "name": "Tm9kZUpTIFJlbW90ZQ=="
      },
      "deviceName": "Tm9kZUpTIFJlbW90ZQ==",
      "isHost": false
    },
    {
      "id": "7c11cc00-3a2a-11ea-8bda-09a15a0e9908",
      "connectTime": 1579376473280,
      "attributes": {
        "name": "Tm9kZUpTIFJlbW90ZQ=="
      },
      "deviceName": "Tm9kZUpTIFJlbW90ZQ==",
      "isHost": false
    },
    {
      "id": "bc72a990-3a2a-11ea-8bda-09a15a0e9908",
      "connectTime": 1579376581289,
      "attributes": {
        "name": "Tm9kZUpTIFJlbW90ZQ=="
      },
      "deviceName": "Tm9kZUpTIFJlbW90ZQ==",
      "isHost": false
    },
    {
      "id": "8ce3e8e0-3a2c-11ea-8bda-09a15a0e9908",
      "connectTime": 1579377360494,
      "attributes": {
        "name": "Tm9kZUpTIFJlbW90ZQ=="
      },
      "deviceName": "Tm9kZUpTIFJlbW90ZQ==",
      "isHost": false
    },
    {
      "id": "dd5f3e00-3a2c-11ea-8bda-09a15a0e9908",
      "connectTime": 1579377495520,
      "attributes": {
        "name": "Tm9kZUpTIFJlbW90ZQ=="
      },
      "deviceName": "Tm9kZUpTIFJlbW90ZQ==",
      "isHost": false
    },
    {
      "id": "10d16880-3a2d-11ea-8bda-09a15a0e9908",
      "connectTime": 1579377581832,
      "attributes": {
        "name": "Tm9kZUpTIFJlbW90ZQ=="
      },
      "deviceName": "Tm9kZUpTIFJlbW90ZQ==",
      "isHost": false
    },
    {
      "id": "2bd9e120-3a2d-11ea-8bda-09a15a0e9908",
      "connectTime": 1579377627186,
      "attributes": {
        "name": "Tm9kZUpTIFJlbW90ZQ=="
      },
      "deviceName": "Tm9kZUpTIFJlbW90ZQ==",
      "isHost": false
    },
    {
      "id": "2ca93f10-3a2d-11ea-8bda-09a15a0e9908",
      "connectTime": 1579377628545,
      "attributes": {
        "name": "Tm9kZUpTIFJlbW90ZQ=="
      },
      "deviceName": "Tm9kZUpTIFJlbW90ZQ==",
      "isHost": false
    },
    {
      "id": "2d025b90-3a2d-11ea-8bda-09a15a0e9908",
      "connectTime": 1579377629129,
      "attributes": {
        "name": "Tm9kZUpTIFJlbW90ZQ=="
      },
      "deviceName": "Tm9kZUpTIFJlbW90ZQ==",
      "isHost": false
    },
    {
      "id": "92c6c1a0-3a2d-11ea-8bda-09a15a0e9908",
      "connectTime": 1579377799866,
      "attributes": {
        "name": "Tm9kZUpTIFJlbW90ZQ=="
      },
      "deviceName": "Tm9kZUpTIFJlbW90ZQ==",
      "isHost": false
    },
    {
      "id": "963c8770-3a2d-11ea-8bda-09a15a0e9908",
      "connectTime": 1579377805671,
      "attributes": {
        "name": "Tm9kZUpTIFJlbW90ZQ=="
      },
      "deviceName": "Tm9kZUpTIFJlbW90ZQ==",
      "isHost": false
    },
    {
      "id": "9a532120-3a2d-11ea-8bda-09a15a0e9908",
      "connectTime": 1579377812530,
      "attributes": {
        "name": "Tm9kZUpTIFJlbW90ZQ=="
      },
      "deviceName": "Tm9kZUpTIFJlbW90ZQ==",
      "isHost": false
    },
    {
      "id": "bc17ff10-3a2d-11ea-8bda-09a15a0e9908",
      "connectTime": 1579377869185,
      "attributes": {
        "name": "Tm9kZUpTIFJlbW90ZQ=="
      },
      "deviceName": "Tm9kZUpTIFJlbW90ZQ==",
      "isHost": false
    },
    {
      "id": "26419400-3a2e-11ea-8bda-09a15a0e9908",
      "connectTime": 1579378047296,
      "attributes": {
        "name": "Tm9kZUpTIFJlbW90ZQ=="
      },
      "deviceName": "Tm9kZUpTIFJlbW90ZQ==",
      "isHost": false
    },
    {
      "id": "27005020-3a2e-11ea-8bda-09a15a0e9908",
      "connectTime": 1579378048546,
      "attributes": {
        "name": "Tm9kZUpTIFJlbW90ZQ=="
      },
      "deviceName": "Tm9kZUpTIFJlbW90ZQ==",
      "isHost": false
    },
    {
      "id": "91517cc0-3a9b-11ea-8bda-09a15a0e9908",
      "connectTime": 1579425042060,
      "attributes": {
        "name": "Tm9kZUpTIFJlbW90ZQ=="
      },
      "deviceName": "Tm9kZUpTIFJlbW90ZQ==",
      "isHost": false
    },
    {
      "id": "91585a90-3a9b-11ea-8bda-09a15a0e9908",
      "connectTime": 1579425042105,
      "attributes": {
        "name": "Tm9kZUpTIFJlbW90ZQ=="
      },
      "deviceName": "Tm9kZUpTIFJlbW90ZQ==",
      "isHost": false
    }
  ]
}
`

**Comment by Toxblh** [comment]
KU6400.. 2016 and unsupported that approach to control.

**Comment by ilteoood** [comment]
You mean websocket?
That's not true, I'm using https://github.com/Ape/samsungctl without any problem

**Comment by Toxblh** [comment]
try the new version with port 8001

**Comment by Toxblh** [comment]
fixed in DM
