### ISSUE TITLE
Last update breaks anything

### ISSUE THREAD

**Issue by satrik** [Toxblh/samsung-tv-control#200]
Hi, 
after the update from 2.0.0 to 2.0.1 my TV wasn't reachable in the Home App.

So I've removed it from Homekit, unpaired it in Homebridge, removed the pairing in the TV settings and tried to add it again. But apart from `discover` and `pair1` nothing works. The TV neither show up in Homebridge nor any chance to get it into Homekit. 

After roll-back to version 2.0.0,  I didn't have any issues. 

```
[TV] UE55J6289:
	model: UE55J6240
```

Greetings 
satrik

**Comment by Toxblh** [comment]
I'm not sure, it's regarding my library. Could you pls double check?

**Comment by satrik** [comment]
Omg, I didn't have seen that this repo is just the library and not the Homebridge plugin 😂 

Sorry 😬
