### ISSUE TITLE
Missing token.txt

### ISSUE THREAD

**Issue by lttin0912** [Toxblh/samsung-tv-control#228]
Hi, I receive the error:
ERROR if (this.SAVE_TOKEN)
Error: ENOENT: no such file or directory

I have to create it manual

**Comment by jaggzh** [comment]
I had the same issue.  I ended up making a 0-length file there.  It then would add a newly-obtained token to the file.
Now, each time I run this, the TV asks for confirmation anyway, and a new token comes in, *but the token.txt file isn't updated*.
More importantly, I'm not sure how to get the tv to accept the token it's just given us.
