### ISSUE TITLE
getting token back

### ISSUE THREAD

**Issue by davidchatting** [Toxblh/samsung-tv-control#3]
Hi - I see that if you use sendKey() without specifying the key it will cause the TV to open a dialogue box to approve the interaction and then print the result back to the console - would it be possible to pass this value back instead please?

Thanks

**Comment by Toxblh** [comment]
Good point. Yes, do it in the evening, or I open for PRs)

**Comment by davidchatting** [comment]
Great! Thank you - and thanks for the library, it's taken be an age to find something that works! I've wrapped it and it it's playing nicely with Node-RED

**Comment by structure7** [comment]
Related: what's the best way to get the TV's token? Thanks for creating this node!

**Comment by Toxblh** [comment]
Now will do that.

**Comment by Toxblh** [comment]
@davidchatting @structure7 
v1.3.0 released
Okay I added method `getToken` you can use that before all for getting a token
I think better (well, this as I use that) save the token to config for future

**Comment by Toxblh** [comment]
If will be any questions - welcome.

**Comment by increddibelly** [comment]
At first Iit didn't seem to work, but when you try to get the token, a permission request dialog appears on the TV for a few seconds. After you confirm, you get a token.
