### ISSUE TITLE
Bug in send code

### ISSUE THREAD

**Issue by bkp7** [Toxblh/samsung-tv-control#81]
When using send, if successful, the callback is called twice. The bug is at line 380 in samsung.ts. If the correct event is received (line 384) then 'done' is called twice. Sorry, I couldn't immediately see the notes on contributing so will leave for someone more familiar with the project to fix/test.

**Comment by Letrab** [comment]
How would you tackle this @Toxblh ? Happy to contribute.

I saw you moved from keeping the WS socket as a global state. But now, the WS socket is not closed on each possible path (error, ...) and thus also created this bug.

I would suggest to move it back to global, but check whether it's still connected on each `send` call?
As e.g. here: https://dev.to/karlhadwen/node-js-websocket-tutorial-real-time-chat-room-using-multiple-clients-24ad (search for `init()`)
