### ISSUE TITLE
TV ask every time i run the script after geving promiss

### ISSUE THREAD

**Issue by Kassan424kh** [Toxblh/samsung-tv-control#87]
<a href="https://ibb.co/gWyvp8Y"><img src="https://i.ibb.co/gWyvp8Y/1604820579504.jpg" alt="1604820579504" border="0"></a>

```js
// import Samsung, { APPS, KEYS } from 'samsung-tv-control'
const { Samsung, KEYS, APPS } = require('samsung-tv-control')

const config = {
  debug: true,
  ip: '192.168.0.100',
  mac: '3968A4CCB172',
  name: '[TV] Q60',
  token: '86454899586366__',
  saveToken: true,
}

const control = new Samsung(config)


async function main() {
  await control.isAvailable()

  let token = await control.getTokenPromise()
  console.log('$$ token:', token)

  await control.sendKeyPromise(KEYS.KEY_POWER)
}

main()
```

````cmd
c:\Users\khali\Desktop> node index.js
````

is there a way to save the application in the tv, as trust

**Comment by Kassan424kh** [comment]
Any ideas

**Comment by d0tkom** [comment]
This means you're either sending an incorrect token, or not sending one at all. Can you show your console output when you run the command?
But I'd try setting saveToken to false, running the script again, allowing the connection on the TV, and when it logs the token to the console, set that token in config, and it should work from then on without any more pop-ups.

**Comment by Kassan424kh** [comment]
thanks @d0tkom very much,

IT WORKS NOW 💪
